apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::496278789073:role/eksctl-skccuser01-nodegroup-stand-NodeInstanceRole-16HOEVRDHSYBQ
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::496278789073:role/CodeBuildSkccUser01
      username: CodeBuildSkccUser01
      groups:
        -system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::496278789073:role/eksctl-skccuser01-nodegroup-stand-NodeInstanceRole-16HOEVRDHSYBQ\n  username: system:node:{{EC2PrivateDNSName}}\n- rolearn: arn:aws:iam::496278789073:role/CodeBuildSkccUser01\n  username: CodeBuildSkccUser01 \n  groups:\n    -system:masters\n","mapUsers":"[]\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2020-09-02T05:27:35Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"857","selfLink":"/api/v1/namespaces/kube-system/configmaps/aws-auth","uid":"3ff6ee71-2cb1-4ab4-b6ef-fb5e5d020d6c"}}
  creationTimestamp: "2020-09-02T05:27:35Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "109884"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 3ff6ee71-2cb1-4ab4-b6ef-fb5e5d020d6c
